"""
100 test cases for the BNS-Only RAG Comparison.

Gold BNS section numbers are the primary applicable sections under BNS_2023.
Cases 1-10 reused from Old-Work/semantic_eval.py; cases 11-100 cover diverse
offense categories: murder, kidnapping, robbery, dacoity, fraud, defamation,
public nuisance, forgery, counterfeiting, sexual offenses, child-related
offenses, offenses against the state, religious offenses, drug offenses, etc.
"""
from typing import Dict, List

TEST_CASES: List[Dict] = [
    # ── Cases 1-10 (original) ───────────────────────────────────────────
    {
        "id": 1,
        "description": "Someone stole my mobile phone from my pocket in a crowded bus.",
        "offense_category": "theft",
        "expected_bns_sections": ["303", "304"],
        "offense_keywords": ["theft", "stealing", "stolen", "pickpocket", "pick-pocket"],
        "key_issues": [
            "movable property",
            "dishonest intention",
            "without consent",
            "taking away",
            "property of another person",
        ],
    },
    {
        "id": 2,
        "description": "A man entered my house at night by breaking the door and took my jewelry.",
        "offense_category": "housebreaking and theft",
        "expected_bns_sections": ["330", "331", "333", "334", "303"],
        "offense_keywords": [
            "housebreaking",
            "house-breaking",
            "trespass",
            "theft",
            "burglary",
            "robbery",
        ],
        "key_issues": [
            "entry into dwelling house",
            "at night",
            "without permission",
            "stealing property",
            "dishonest intention",
        ],
    },
    {
        "id": 3,
        "description": "My neighbor keeps threatening to beat me if I use the common parking area.",
        "offense_category": "criminal intimidation",
        "expected_bns_sections": ["351", "356"],
        "offense_keywords": [
            "criminal intimidation",
            "threatening",
            "threats",
            "fear of injury",
            "intimidate",
        ],
        "key_issues": [
            "threats to cause harm",
            "create fear",
            "intent to force or prevent an act",
            "wrongful intimidation",
        ],
    },
    {
        "id": 4,
        "description": "Two people started fighting on the street and one hit the other with a stick causing injuries.",
        "offense_category": "assault and causing hurt",
        "expected_bns_sections": ["115", "116", "351"],
        "offense_keywords": [
            "assault",
            "hurt",
            "grievous hurt",
            "physical attack",
            "beating",
            "injury",
        ],
        "key_issues": [
            "physical assault",
            "use of weapon or stick",
            "causing bodily injury",
            "intention or knowledge to cause hurt",
        ],
    },
    {
        "id": 5,
        "description": "A person sent me abusive and vulgar messages repeatedly on WhatsApp.",
        "offense_category": "harassment and obscene messages",
        "expected_bns_sections": ["296", "356", "351"],
        "offense_keywords": [
            "harassment",
            "obscene messages",
            "abusive language",
            "insult",
            "defamation",
            "cyber bullying",
        ],
        "key_issues": [
            "repeated messages",
            "abusive or vulgar content",
            "intent to insult or annoy",
            "mental harassment",
        ],
    },
    {
        "id": 6,
        "description": "Someone forged my signature on a cheque and withdrew money from my account.",
        "offense_category": "forgery and cheque fraud",
        "expected_bns_sections": ["318", "319", "336"],
        "offense_keywords": [
            "forgery",
            "fraud",
            "fake signature",
            "cheque",
            "cheque fraud",
            "dishonestly",
        ],
        "key_issues": [
            "forged signature",
            "cheque used without authority",
            "dishonest withdrawal of money",
            "false document",
        ],
    },
    {
        "id": 7,
        "description": "My landlord locked me out of my rented room without any notice and kept my belongings inside.",
        "offense_category": "unlawful eviction / wrongful confinement",
        "expected_bns_sections": ["126", "329", "351"],
        "offense_keywords": [
            "illegal eviction",
            "unlawful eviction",
            "wrongful confinement",
            "locking out",
            "landlord dispute",
        ],
        "key_issues": [
            "landlord locked tenant out",
            "no notice",
            "personal belongings inside",
            "depriving access to property",
        ],
    },
    {
        "id": 8,
        "description": "A group of people damaged my shop during a protest by throwing stones and breaking the glass.",
        "offense_category": "mischief and property damage",
        "expected_bns_sections": ["324", "326", "336", "337"],
        "offense_keywords": [
            "mischief",
            "damage to property",
            "vandalism",
            "rioting",
            "destruction",
        ],
        "key_issues": [
            "damage to shop",
            "throwing stones",
            "breaking glass",
            "intentional destruction of property",
        ],
    },
    {
        "id": 9,
        "description": "A stranger keeps calling and sending messages threatening to burn my shop if I do not pay him money.",
        "offense_category": "extortion / criminal intimidation",
        "expected_bns_sections": ["308", "309", "356"],
        "offense_keywords": [
            "extortion",
            "criminal intimidation",
            "threatening",
            "threat to burn",
            "demanding money",
        ],
        "key_issues": [
            "threat to burn shop",
            "demanding money",
            "creating fear of injury to property",
            "forcing payment",
        ],
    },
    {
        "id": 10,
        "description": "Someone hacked my social media account and posted offensive content using my name.",
        "offense_category": "cybercrime / hacking and defamation",
        "expected_bns_sections": ["318", "319", "356"],
        "offense_keywords": [
            "hacking",
            "unauthorized access",
            "cybercrime",
            "defamation",
            "impersonation",
            "social media account",
        ],
        "key_issues": [
            "account accessed without permission",
            "posting offensive content",
            "damage to reputation",
            "misuse of identity",
        ],
    },
    # ── Cases 11-20: Murder / Culpable Homicide / Attempt to Murder ─────
    {
        "id": 11,
        "description": "During a land dispute my uncle stabbed my father multiple times with a knife and he died on the spot.",
        "offense_category": "murder",
        "expected_bns_sections": ["101", "103"],
        "offense_keywords": ["murder", "stabbing", "killing", "homicide", "death"],
        "key_issues": [
            "intentional causing of death",
            "use of deadly weapon",
            "premeditated act",
        ],
    },
    {
        "id": 12,
        "description": "A man poured acid on a woman's face after she rejected his marriage proposal and she later succumbed to injuries.",
        "offense_category": "murder and acid attack",
        "expected_bns_sections": ["101", "103", "124"],
        "offense_keywords": ["acid attack", "murder", "death", "disfigurement", "rejected proposal"],
        "key_issues": [
            "causing death",
            "acid attack causing grievous hurt",
            "rejected relationship as motive",
            "intention to kill or cause grievous bodily harm",
        ],
    },
    {
        "id": 13,
        "description": "My neighbor hit my brother on the head with an iron rod during a heated argument; he is in ICU and may not survive.",
        "offense_category": "attempt to murder",
        "expected_bns_sections": ["109", "117", "118"],
        "offense_keywords": ["attempt to murder", "iron rod", "head injury", "ICU", "grievous hurt"],
        "key_issues": [
            "intention to cause death",
            "use of dangerous weapon",
            "grievous hurt to head",
            "life-threatening injury",
        ],
    },
    {
        "id": 14,
        "description": "Two men got into a drunken fight and one pushed the other off a bridge, causing his death.",
        "offense_category": "culpable homicide",
        "expected_bns_sections": ["100", "105"],
        "offense_keywords": ["culpable homicide", "pushed off bridge", "death", "drunken fight", "falling"],
        "key_issues": [
            "act likely to cause death",
            "knowledge of danger",
            "death caused without premeditation",
            "intoxication",
        ],
    },
    {
        "id": 15,
        "description": "A bus driver was driving recklessly at high speed and ran over a pedestrian who died on the spot.",
        "offense_category": "death by negligence",
        "expected_bns_sections": ["106", "281"],
        "offense_keywords": ["rash driving", "negligence", "death", "pedestrian", "accident"],
        "key_issues": [
            "rash and negligent driving",
            "causing death",
            "duty of care on public road",
            "endangering life",
        ],
    },
    {
        "id": 16,
        "description": "A wife was continuously tortured by her husband and in-laws for dowry; she was found hanging in her room within two years of marriage.",
        "offense_category": "dowry death",
        "expected_bns_sections": ["80", "85", "86"],
        "offense_keywords": ["dowry death", "cruelty", "suicide", "husband", "in-laws", "dowry demand"],
        "key_issues": [
            "death within seven years of marriage",
            "cruelty for dowry",
            "presumption of dowry death",
            "harassment by husband and relatives",
        ],
    },
    {
        "id": 17,
        "description": "A teenager posted on social media encouraging her classmate to commit suicide; the classmate later took her own life.",
        "offense_category": "abetment of suicide",
        "expected_bns_sections": ["108", "107"],
        "offense_keywords": ["abetment", "suicide", "instigating", "encouraging", "social media"],
        "key_issues": [
            "instigating suicide",
            "abetment through words or actions",
            "victim was minor",
            "mental pressure leading to death",
        ],
    },
    {
        "id": 18,
        "description": "A life-convict on parole got into a fight and strangled another person to death.",
        "offense_category": "murder by life-convict",
        "expected_bns_sections": ["101", "104"],
        "offense_keywords": ["murder", "life-convict", "parole", "strangled", "killing"],
        "key_issues": [
            "murder committed by life-convict",
            "enhanced punishment",
            "intention to cause death",
        ],
    },
    {
        "id": 19,
        "description": "A man fired his licensed gun at his business partner during a heated dispute but the bullet missed narrowly.",
        "offense_category": "attempt to murder",
        "expected_bns_sections": ["109", "130"],
        "offense_keywords": ["attempt to murder", "gunshot", "fired gun", "narrow miss", "assault"],
        "key_issues": [
            "intention to kill",
            "use of firearm",
            "act done towards commission of murder",
            "narrow escape",
        ],
    },
    {
        "id": 20,
        "description": "A cook mixed rat poison into the food served at a party and three guests died after consuming it.",
        "offense_category": "murder by poisoning",
        "expected_bns_sections": ["101", "103", "123"],
        "offense_keywords": ["murder", "poisoning", "rat poison", "food", "death", "multiple victims"],
        "key_issues": [
            "premeditated poisoning",
            "intention to cause death",
            "multiple victims",
            "use of poison as weapon",
        ],
    },
    # ── Cases 21-30: Kidnapping / Abduction / Trafficking ───────────────
    {
        "id": 21,
        "description": "My 8-year-old son was taken away by unknown persons from outside his school and we received a ransom call demanding ten lakh rupees.",
        "offense_category": "kidnapping for ransom",
        "expected_bns_sections": ["137", "138", "308"],
        "offense_keywords": ["kidnapping", "ransom", "child", "abduction", "school"],
        "key_issues": [
            "kidnapping of minor",
            "ransom demand",
            "taking from lawful guardianship",
            "extortion linked to kidnapping",
        ],
    },
    {
        "id": 22,
        "description": "A young woman was lured with a fake job offer and trafficked to another state where she was forced into prostitution.",
        "offense_category": "human trafficking",
        "expected_bns_sections": ["138", "144", "98"],
        "offense_keywords": ["trafficking", "forced prostitution", "fake job", "exploitation", "luring"],
        "key_issues": [
            "deception for trafficking",
            "sexual exploitation",
            "transportation across state",
            "compulsion and coercion",
        ],
    },
    {
        "id": 23,
        "description": "A gang kidnapped children from railway stations and maimed them to use for organized begging.",
        "offense_category": "kidnapping and maiming for begging",
        "expected_bns_sections": ["137", "139", "95"],
        "offense_keywords": ["kidnapping", "maiming", "begging", "children", "gang", "exploitation"],
        "key_issues": [
            "kidnapping of minors",
            "causing physical disability",
            "employing children for begging",
            "organized crime against children",
        ],
    },
    {
        "id": 24,
        "description": "My teenage daughter was taken away by a man she met online without my knowledge or consent.",
        "offense_category": "kidnapping from lawful guardianship",
        "expected_bns_sections": ["137", "138"],
        "offense_keywords": ["kidnapping", "minor", "online grooming", "without consent", "guardianship"],
        "key_issues": [
            "taking minor from lawful guardian",
            "without consent of guardian",
            "online enticement",
        ],
    },
    {
        "id": 25,
        "description": "An auto-rickshaw driver forcibly took a woman passenger to an isolated area against her will.",
        "offense_category": "abduction",
        "expected_bns_sections": ["138", "127", "74"],
        "offense_keywords": ["abduction", "forcible transport", "isolated area", "woman", "auto-rickshaw"],
        "key_issues": [
            "compelling person to go from one place to another",
            "use of force",
            "wrongful confinement",
            "threat to woman's safety",
        ],
    },
    {
        "id": 26,
        "description": "A child under ten was stolen from her parents at a mela and later found being sold to a couple in another city.",
        "offense_category": "kidnapping and selling of child",
        "expected_bns_sections": ["97", "98", "137"],
        "offense_keywords": ["child stealing", "kidnapping", "selling child", "mela", "trafficking"],
        "key_issues": [
            "kidnapping child under ten",
            "intent to steal from person of child",
            "selling minor",
            "commercial exploitation",
        ],
    },
    {
        "id": 27,
        "description": "A factory owner brought migrant workers from Bihar with false promises and made them work without pay under locked conditions.",
        "offense_category": "unlawful compulsory labour",
        "expected_bns_sections": ["146", "144", "127"],
        "offense_keywords": ["bonded labour", "forced labour", "false promises", "no wages", "confinement"],
        "key_issues": [
            "compulsory labour without consent",
            "wrongful confinement",
            "exploitation of migrant workers",
            "deception regarding employment",
        ],
    },
    {
        "id": 28,
        "description": "A man kidnapped his ex-wife's 6-year-old child from her home and fled to a different state.",
        "offense_category": "kidnapping from lawful guardianship",
        "expected_bns_sections": ["137", "329"],
        "offense_keywords": ["kidnapping", "child custody", "ex-wife", "trespass", "minor"],
        "key_issues": [
            "taking child from lawful guardian",
            "custody dispute",
            "crossing state borders with minor",
        ],
    },
    {
        "id": 29,
        "description": "Several girls from a village were promised nursing jobs abroad but were taken to a city and forced into the flesh trade.",
        "offense_category": "trafficking for sexual exploitation",
        "expected_bns_sections": ["144", "98", "138"],
        "offense_keywords": ["trafficking", "sexual exploitation", "false promise", "flesh trade", "girls"],
        "key_issues": [
            "fraud used to recruit victims",
            "trafficking for prostitution",
            "exploitation of vulnerable persons",
            "transportation of victims",
        ],
    },
    {
        "id": 30,
        "description": "A couple bought a 4-year-old boy from an orphanage caretaker who had no authority to sell children.",
        "offense_category": "buying child for exploitation",
        "expected_bns_sections": ["99", "97"],
        "offense_keywords": ["buying child", "illegal adoption", "orphanage", "child selling", "trafficking"],
        "key_issues": [
            "buying a minor",
            "unauthorized sale of child",
            "exploitation of vulnerable child",
        ],
    },
    # ── Cases 31-40: Robbery / Dacoity / Extortion ──────────────────────
    {
        "id": 31,
        "description": "Three men on a motorcycle snatched my gold chain while I was walking on the road and one of them showed a knife.",
        "offense_category": "robbery / snatching",
        "expected_bns_sections": ["309", "304", "303"],
        "offense_keywords": ["robbery", "snatching", "chain", "knife", "motorcycle"],
        "key_issues": [
            "use of force or threat",
            "snatching property",
            "possession of weapon",
            "theft with intimidation",
        ],
    },
    {
        "id": 32,
        "description": "A gang of seven armed men broke into a jewellery shop at night, tied up the watchman, and looted all the gold and cash.",
        "offense_category": "dacoity",
        "expected_bns_sections": ["310", "311", "127"],
        "offense_keywords": ["dacoity", "armed gang", "looting", "jewellery shop", "tied up"],
        "key_issues": [
            "five or more persons committing robbery",
            "use of weapons",
            "wrongful restraint of watchman",
            "looting of valuable property",
            "nighttime entry",
        ],
    },
    {
        "id": 33,
        "description": "A local goon demands monthly protection money from shopkeepers in my area and beats those who refuse to pay.",
        "offense_category": "extortion",
        "expected_bns_sections": ["308", "115", "351"],
        "offense_keywords": ["extortion", "protection money", "goon", "beating", "shopkeeper"],
        "key_issues": [
            "putting person in fear of injury",
            "dishonest inducement to deliver property",
            "regular collection of money by intimidation",
            "physical violence for refusal",
        ],
    },
    {
        "id": 34,
        "description": "While returning from an ATM at night, two people held me at gunpoint and took away all my cash and debit card.",
        "offense_category": "robbery with deadly weapon",
        "expected_bns_sections": ["309", "311", "312"],
        "offense_keywords": ["robbery", "gunpoint", "ATM", "cash", "deadly weapon"],
        "key_issues": [
            "robbery with use of firearm",
            "threat of death",
            "taking property by force",
            "nighttime assault",
        ],
    },
    {
        "id": 35,
        "description": "A group of dacoits attacked a village, looted houses, and assaulted several villagers causing serious injuries.",
        "offense_category": "dacoity with attempt to cause death or grievous hurt",
        "expected_bns_sections": ["310", "311", "117"],
        "offense_keywords": ["dacoity", "village attack", "looting", "assault", "grievous injuries"],
        "key_issues": [
            "gang robbery by five or more persons",
            "attempt to cause death or grievous hurt",
            "looting multiple houses",
            "mass assault on villagers",
        ],
    },
    {
        "id": 36,
        "description": "Someone showed me a knife in a train and forcibly took my laptop bag and wallet.",
        "offense_category": "robbery in means of transportation",
        "expected_bns_sections": ["309", "134", "305"],
        "offense_keywords": ["robbery", "knife", "train", "laptop", "wallet", "force"],
        "key_issues": [
            "theft with use of force",
            "weapon used to intimidate",
            "property taken from person",
            "on public transport",
        ],
    },
    {
        "id": 37,
        "description": "A person claiming to be a police officer stopped my car, showed a fake ID, and demanded cash to let me go without a 'challan'.",
        "offense_category": "extortion by impersonation of public servant",
        "expected_bns_sections": ["308", "204", "319"],
        "offense_keywords": ["extortion", "fake police", "impersonation", "bribery", "challan"],
        "key_issues": [
            "impersonating public servant",
            "extortion under colour of office",
            "cheating by personation",
            "dishonest demand for money",
        ],
    },
    {
        "id": 38,
        "description": "Armed robbers hijacked a delivery truck on the highway, tied the driver, and stole the entire consignment of electronics.",
        "offense_category": "highway robbery",
        "expected_bns_sections": ["309", "311", "127", "303"],
        "offense_keywords": ["highway robbery", "hijacking", "armed", "truck", "consignment"],
        "key_issues": [
            "robbery on public highway",
            "use of arms",
            "wrongful restraint of driver",
            "theft of goods in transit",
        ],
    },
    {
        "id": 39,
        "description": "My servant stole cash and gold ornaments from my almirah using a duplicate key he had secretly made.",
        "offense_category": "theft by servant",
        "expected_bns_sections": ["306", "303", "305"],
        "offense_keywords": ["theft", "servant", "duplicate key", "gold", "breach of trust"],
        "key_issues": [
            "theft by clerk or servant",
            "property in possession of master",
            "use of duplicate key",
            "breach of trust",
        ],
    },
    {
        "id": 40,
        "description": "A known criminal gang has been robbing buses on rural roads; they stop the bus, beat passengers, and take all valuables.",
        "offense_category": "belonging to gang of robbers",
        "expected_bns_sections": ["313", "309", "310"],
        "offense_keywords": ["gang", "robbers", "bus robbery", "rural", "valuables", "gang crime"],
        "key_issues": [
            "membership of gang of robbers",
            "serial robbery of public transport",
            "use of violence",
            "organised crime",
        ],
    },
    # ── Cases 41-50: Fraud / Cheating / Misappropriation ────────────────
    {
        "id": 41,
        "description": "A real-estate agent collected advance money for a flat that he had already sold to someone else.",
        "offense_category": "cheating",
        "expected_bns_sections": ["318", "319"],
        "offense_keywords": ["cheating", "fraud", "advance money", "flat", "double sale"],
        "key_issues": [
            "dishonest inducement to part with property",
            "false representation of ownership",
            "fraudulent intention",
        ],
    },
    {
        "id": 42,
        "description": "An accountant in our company siphoned off funds by creating fake invoices and transferring money to his personal account.",
        "offense_category": "criminal breach of trust and falsification of accounts",
        "expected_bns_sections": ["314", "344", "316"],
        "offense_keywords": ["embezzlement", "fake invoices", "breach of trust", "siphoning", "accounts"],
        "key_issues": [
            "dishonest misappropriation of entrusted property",
            "falsification of financial records",
            "abuse of position",
            "fraudulent transfer of funds",
        ],
    },
    {
        "id": 43,
        "description": "I purchased a used car online; the seller provided forged RC and insurance documents and the car turned out to be stolen.",
        "offense_category": "cheating and forgery",
        "expected_bns_sections": ["318", "336", "340"],
        "offense_keywords": ["forged documents", "stolen car", "cheating", "fake RC", "online fraud"],
        "key_issues": [
            "fraudulent sale of stolen property",
            "forged registration documents",
            "using forged documents as genuine",
            "deceiving buyer",
        ],
    },
    {
        "id": 44,
        "description": "A courier agent collected valuables for delivery but never delivered them and switched off his phone.",
        "offense_category": "criminal misappropriation",
        "expected_bns_sections": ["314", "318"],
        "offense_keywords": ["misappropriation", "courier", "valuables", "non-delivery", "absconding"],
        "key_issues": [
            "dishonest misappropriation of property",
            "entrusted property not returned",
            "absconding after collecting goods",
        ],
    },
    {
        "id": 45,
        "description": "A man called my elderly mother pretending to be a bank officer and got her to share OTP; Rs 2 lakh was withdrawn from her account.",
        "offense_category": "cyber fraud / cheating by personation",
        "expected_bns_sections": ["319", "318", "351"],
        "offense_keywords": ["phishing", "OTP fraud", "bank officer", "elderly victim", "cyber fraud"],
        "key_issues": [
            "impersonation of bank official",
            "inducing victim to share confidential information",
            "fraudulent withdrawal of funds",
            "targeting vulnerable elderly person",
        ],
    },
    {
        "id": 46,
        "description": "My business partner secretly transferred company funds to his personal account and denied any knowledge of it.",
        "offense_category": "criminal breach of trust",
        "expected_bns_sections": ["314", "316"],
        "offense_keywords": ["breach of trust", "embezzlement", "company funds", "partner", "transfer"],
        "key_issues": [
            "misappropriation of jointly entrusted funds",
            "breach of fiduciary duty",
            "dishonest conversion",
        ],
    },
    {
        "id": 47,
        "description": "A fake charity collected donations from the public for flood relief but used all the money for personal expenses.",
        "offense_category": "cheating and misappropriation",
        "expected_bns_sections": ["318", "314"],
        "offense_keywords": ["fake charity", "donation fraud", "misuse of funds", "cheating", "flood relief"],
        "key_issues": [
            "fraudulent representation",
            "collecting money under false pretences",
            "dishonest use of donated funds",
        ],
    },
    {
        "id": 48,
        "description": "A jeweller replaced my real diamond with a fake one during a repair and returned the fake stone claiming it was mine.",
        "offense_category": "cheating",
        "expected_bns_sections": ["318", "314"],
        "offense_keywords": ["cheating", "fake diamond", "jeweller", "fraud", "swap", "dishonesty"],
        "key_issues": [
            "dishonest substitution of property",
            "fraudulent deception",
            "breach of trust by bailee",
        ],
    },
    {
        "id": 49,
        "description": "I paid a travel agent Rs 3 lakh for a holiday package but no bookings were ever made and he is now unreachable.",
        "offense_category": "cheating and absconding",
        "expected_bns_sections": ["318", "314"],
        "offense_keywords": ["travel fraud", "cheating", "advance payment", "no bookings", "absconding"],
        "key_issues": [
            "fraudulent inducement to part with money",
            "services never provided",
            "absconding to avoid accountability",
        ],
    },
    {
        "id": 50,
        "description": "A builder collected money from twenty buyers for the same ten flats by showing forged allotment letters.",
        "offense_category": "cheating and forgery",
        "expected_bns_sections": ["318", "336", "338"],
        "offense_keywords": ["real estate fraud", "builder", "forged allotment", "double booking", "cheating"],
        "key_issues": [
            "large-scale cheating of home buyers",
            "forged allotment letters",
            "sale of same property to multiple buyers",
            "fraudulent intent",
        ],
    },
    # ── Cases 51-57: Defamation / Public Nuisance / Obscenity ───────────
    {
        "id": 51,
        "description": "A person published a false article in the newspaper accusing me of corruption without any evidence, damaging my reputation.",
        "offense_category": "defamation",
        "expected_bns_sections": ["356"],
        "offense_keywords": ["defamation", "false accusation", "newspaper", "reputation", "corruption"],
        "key_issues": [
            "publishing false imputation",
            "harm to reputation",
            "making or publishing defamatory content",
        ],
    },
    {
        "id": 52,
        "description": "A factory in our residential area releases toxic fumes every night causing breathing problems for all the residents.",
        "offense_category": "public nuisance",
        "expected_bns_sections": ["270", "280", "292"],
        "offense_keywords": ["pollution", "toxic fumes", "factory", "public nuisance", "health hazard"],
        "key_issues": [
            "act causing common injury or danger to public",
            "making atmosphere noxious to health",
            "continuing public nuisance",
        ],
    },
    {
        "id": 53,
        "description": "Someone is running an illegal lottery office in our neighborhood and many people have lost money.",
        "offense_category": "keeping lottery office",
        "expected_bns_sections": ["297"],
        "offense_keywords": ["illegal lottery", "gambling", "lottery office", "money loss", "neighborhood"],
        "key_issues": [
            "keeping an office for lottery",
            "illegal gambling operation",
            "public being induced to gamble",
        ],
    },
    {
        "id": 54,
        "description": "A person was singing obscene songs and making vulgar gestures in a public park in front of women and children.",
        "offense_category": "obscene acts in public",
        "expected_bns_sections": ["296", "79"],
        "offense_keywords": ["obscene songs", "vulgar gestures", "public place", "women", "indecency"],
        "key_issues": [
            "obscene acts in public place",
            "annoyance to others",
            "insulting modesty of women",
        ],
    },
    {
        "id": 55,
        "description": "My ex-boyfriend shared my private photographs on social media and created a fake profile using my pictures.",
        "offense_category": "defamation and voyeurism",
        "expected_bns_sections": ["356", "77", "294"],
        "offense_keywords": ["revenge porn", "private photos", "fake profile", "defamation", "voyeurism"],
        "key_issues": [
            "sharing private images without consent",
            "harm to reputation and dignity",
            "voyeuristic content",
            "creating fake identity",
        ],
    },
    {
        "id": 56,
        "description": "A shop is openly selling obscene magazines and DVDs to school children near a school campus.",
        "offense_category": "sale of obscene material to children",
        "expected_bns_sections": ["294", "295"],
        "offense_keywords": ["obscene material", "children", "school", "sale of DVDs", "magazines"],
        "key_issues": [
            "selling obscene objects",
            "sale specifically to minors",
            "near educational institution",
        ],
    },
    {
        "id": 57,
        "description": "A man standing on the road deliberately shows obscene images on his phone to women passing by.",
        "offense_category": "sexual harassment and obscene acts",
        "expected_bns_sections": ["75", "296", "79"],
        "offense_keywords": ["sexual harassment", "obscene images", "women", "public place", "showing"],
        "key_issues": [
            "unwelcome sexual behaviour",
            "showing pornographic material",
            "insulting modesty of woman",
        ],
    },
    # ── Cases 58-65: Sexual Offences ────────────────────────────────────
    {
        "id": 58,
        "description": "A woman was raped by a man who broke into her house late at night when she was alone.",
        "offense_category": "rape and housebreaking",
        "expected_bns_sections": ["63", "65", "330"],
        "offense_keywords": ["rape", "housebreaking", "sexual assault", "night", "alone"],
        "key_issues": [
            "sexual intercourse without consent",
            "entry into dwelling house",
            "nighttime offence",
            "aggravated form of sexual assault",
        ],
    },
    {
        "id": 59,
        "description": "A college professor asked a female student for sexual favours in exchange for better grades.",
        "offense_category": "sexual harassment and abuse of authority",
        "expected_bns_sections": ["75", "68"],
        "offense_keywords": ["sexual harassment", "quid pro quo", "professor", "student", "authority"],
        "key_issues": [
            "demand for sexual favours",
            "abuse of position of authority",
            "unwelcome sexual advance",
        ],
    },
    {
        "id": 60,
        "description": "A man has been following a woman from her office to her home daily, sending unwanted gifts, and watching her through binoculars.",
        "offense_category": "stalking and voyeurism",
        "expected_bns_sections": ["78", "77"],
        "offense_keywords": ["stalking", "following", "voyeurism", "surveillance", "unwanted contact"],
        "key_issues": [
            "repeated following or contacting",
            "monitoring movements",
            "watching private acts",
            "causing fear or distress",
        ],
    },
    {
        "id": 61,
        "description": "A man grabbed a woman's dupatta and tried to disrobe her in a market while others watched.",
        "offense_category": "assault to disrobe woman",
        "expected_bns_sections": ["76", "74"],
        "offense_keywords": ["disrobing", "assault", "modesty", "woman", "public place"],
        "key_issues": [
            "assault with intent to disrobe",
            "outraging modesty of woman",
            "use of criminal force",
        ],
    },
    {
        "id": 62,
        "description": "A married man had sexual intercourse with his wife during judicial separation against her will.",
        "offense_category": "sexual intercourse during separation",
        "expected_bns_sections": ["67"],
        "offense_keywords": ["marital rape", "judicial separation", "sexual intercourse", "without consent"],
        "key_issues": [
            "sexual intercourse by husband during separation",
            "absence of wife's consent",
            "relationship does not negate offence during separation",
        ],
    },
    {
        "id": 63,
        "description": "A man secretly installed a hidden camera in the women's changing room of a gym to record videos.",
        "offense_category": "voyeurism",
        "expected_bns_sections": ["77"],
        "offense_keywords": ["hidden camera", "voyeurism", "recording", "changing room", "privacy"],
        "key_issues": [
            "watching or capturing private acts",
            "without consent",
            "invasion of privacy",
        ],
    },
    {
        "id": 64,
        "description": "A man deceived a woman into believing they were lawfully married and cohabited with her for months.",
        "offense_category": "deceitful cohabitation",
        "expected_bns_sections": ["81", "83"],
        "offense_keywords": ["deceit", "false marriage", "cohabitation", "fraud", "woman"],
        "key_issues": [
            "inducing false belief of lawful marriage",
            "fraudulent marriage ceremony",
            "sexual relationship by deception",
        ],
    },
    {
        "id": 65,
        "description": "A man who is already married performed a second marriage with another woman without disclosing his first marriage.",
        "offense_category": "bigamy",
        "expected_bns_sections": ["82"],
        "offense_keywords": ["bigamy", "second marriage", "already married", "concealment", "fraud"],
        "key_issues": [
            "marrying during lifetime of existing spouse",
            "concealment of prior marriage",
            "void marriage",
        ],
    },
    # ── Cases 66-72: Child-related Offences ─────────────────────────────
    {
        "id": 66,
        "description": "A woman left her newborn baby in a dustbin near the hospital and disappeared.",
        "offense_category": "exposure and abandonment of child",
        "expected_bns_sections": ["93", "94"],
        "offense_keywords": ["abandonment", "newborn", "exposure", "dustbin", "child"],
        "key_issues": [
            "abandonment of child under twelve",
            "intent to wholly abandon child",
            "exposure to danger",
        ],
    },
    {
        "id": 67,
        "description": "A begging ring operator hired several children aged 7-10 to beg at traffic signals and took all the money they collected.",
        "offense_category": "employing children to commit offence",
        "expected_bns_sections": ["95", "139"],
        "offense_keywords": ["child labour", "begging", "exploitation", "hiring children", "trafficking"],
        "key_issues": [
            "employing or engaging child to commit offence",
            "exploitation of minors",
            "keeping children for begging",
        ],
    },
    {
        "id": 68,
        "description": "A couple secretly delivered a baby and disposed of the body to conceal the birth from neighbours.",
        "offense_category": "concealment of birth",
        "expected_bns_sections": ["94"],
        "offense_keywords": ["concealment of birth", "disposal of body", "secret delivery", "newborn"],
        "key_issues": [
            "secret disposal of dead body of child",
            "concealing the fact of birth",
        ],
    },
    {
        "id": 69,
        "description": "A minor girl aged 14 was procured by a broker and supplied to a client for sexual exploitation.",
        "offense_category": "procuration of minor",
        "expected_bns_sections": ["96", "98"],
        "offense_keywords": ["procuration", "minor girl", "sexual exploitation", "broker", "prostitution"],
        "key_issues": [
            "procuring minor for illicit intercourse",
            "selling child for prostitution",
            "commercial sexual exploitation of minor",
        ],
    },
    {
        "id": 70,
        "description": "A doctor performed an abortion on a woman in her eighth month of pregnancy without medical justification, and the baby died.",
        "offense_category": "causing death of unborn child",
        "expected_bns_sections": ["92", "88"],
        "offense_keywords": ["abortion", "miscarriage", "unborn child", "doctor", "death"],
        "key_issues": [
            "causing death of quick unborn child",
            "act amounting to culpable homicide",
            "causing miscarriage without justification",
        ],
    },
    {
        "id": 71,
        "description": "A woman was forcibly given medicine by her mother-in-law to cause a miscarriage because the family wanted a boy child.",
        "offense_category": "causing miscarriage without consent",
        "expected_bns_sections": ["89", "85"],
        "offense_keywords": ["forced miscarriage", "without consent", "sex selection", "mother-in-law", "cruelty"],
        "key_issues": [
            "causing miscarriage without woman's consent",
            "cruelty by relative of husband",
            "coercion and force",
        ],
    },
    {
        "id": 72,
        "description": "A 5-year-old child was enticed with chocolates by a neighbour who then kept the child locked in his house for two days.",
        "offense_category": "kidnapping of minor",
        "expected_bns_sections": ["137", "127"],
        "offense_keywords": ["kidnapping", "minor", "enticement", "confinement", "child"],
        "key_issues": [
            "taking minor from lawful guardianship",
            "enticement of child",
            "wrongful confinement",
        ],
    },
    # ── Cases 73-80: Offences Against the State / Rioting / Election ────
    {
        "id": 73,
        "description": "A group posted online manifestos calling people to take up arms against the Indian government.",
        "offense_category": "waging war against government",
        "expected_bns_sections": ["147", "152"],
        "offense_keywords": ["sedition", "war against state", "arms", "anti-national", "manifesto"],
        "key_issues": [
            "waging or attempting to wage war against government",
            "endangering sovereignty and integrity of India",
            "incitement to armed rebellion",
        ],
    },
    {
        "id": 74,
        "description": "During a village election, a candidate distributed cash and liquor to voters to get their votes.",
        "offense_category": "electoral bribery",
        "expected_bns_sections": ["170", "173"],
        "offense_keywords": ["bribery", "election", "cash for votes", "liquor", "corruption"],
        "key_issues": [
            "bribery in connection with election",
            "inducing voters with gratification",
            "corrupt electoral practice",
        ],
    },
    {
        "id": 75,
        "description": "A mob of about 200 people armed with sticks and swords attacked shops belonging to a particular community after a rumour spread on social media.",
        "offense_category": "rioting and promoting enmity",
        "expected_bns_sections": ["189", "191", "196"],
        "offense_keywords": ["rioting", "communal violence", "unlawful assembly", "mob", "enmity"],
        "key_issues": [
            "unlawful assembly with common object",
            "rioting with deadly weapons",
            "promoting enmity between groups",
            "communal targeting",
        ],
    },
    {
        "id": 76,
        "description": "A man voted in the election using someone else's identity card and later the real voter was turned away at the booth.",
        "offense_category": "personation at election",
        "expected_bns_sections": ["172", "174"],
        "offense_keywords": ["voter fraud", "personation", "identity card", "election", "impersonation"],
        "key_issues": [
            "personation at election",
            "using another person's electoral right",
            "fraudulent voting",
        ],
    },
    {
        "id": 77,
        "description": "A political leader gave a speech asking Hindus and Muslims to fight each other and burn each other's shops.",
        "offense_category": "promoting enmity between groups",
        "expected_bns_sections": ["196", "197", "353"],
        "offense_keywords": ["hate speech", "communal enmity", "incitement", "religion", "violence"],
        "key_issues": [
            "promoting enmity on grounds of religion",
            "prejudicial to national integration",
            "statements conducing to public mischief",
        ],
    },
    {
        "id": 78,
        "description": "Two groups had a public brawl in the market with sticks and stones causing panic among bystanders.",
        "offense_category": "affray",
        "expected_bns_sections": ["194", "131"],
        "offense_keywords": ["affray", "public fight", "brawl", "sticks", "stones", "panic"],
        "key_issues": [
            "fighting in public place",
            "disturbing public peace",
            "causing terror to the public",
        ],
    },
    {
        "id": 79,
        "description": "A man wearing a police uniform set up a fake checkpoint and was collecting fines from truck drivers on a national highway.",
        "offense_category": "impersonation of public servant",
        "expected_bns_sections": ["204", "205", "308"],
        "offense_keywords": ["impersonation", "fake police", "uniform", "extortion", "checkpoint"],
        "key_issues": [
            "personating a public servant",
            "wearing garb of public servant with fraudulent intent",
            "extortion under false authority",
        ],
    },
    {
        "id": 80,
        "description": "A government clerk intentionally prepared a false caste certificate for someone in exchange for a bribe.",
        "offense_category": "public servant making false document",
        "expected_bns_sections": ["201", "336", "170"],
        "offense_keywords": ["false certificate", "public servant", "bribery", "caste certificate", "fraud"],
        "key_issues": [
            "public servant framing incorrect document",
            "forgery of official document",
            "bribery to public servant",
            "intent to cause injury or benefit",
        ],
    },
    # ── Cases 81-87: Religious Offences / Trespass / Misc ───────────────
    {
        "id": 81,
        "description": "Someone entered the temple at night and smeared black paint on the idol and wrote offensive graffiti on the walls.",
        "offense_category": "defiling place of worship",
        "expected_bns_sections": ["298", "299", "329"],
        "offense_keywords": ["temple", "defiling", "idol", "graffiti", "religious offence"],
        "key_issues": [
            "injuring or defiling place of worship",
            "insulting religious feelings",
            "criminal trespass",
        ],
    },
    {
        "id": 82,
        "description": "A person loudly abused and mocked the religious practices of another community during their festival procession.",
        "offense_category": "wounding religious feelings",
        "expected_bns_sections": ["302", "299"],
        "offense_keywords": ["religious insult", "blasphemy", "mocking", "festival", "community"],
        "key_issues": [
            "uttering words to wound religious feelings",
            "deliberate and malicious intent",
            "outraging religious sentiments",
        ],
    },
    {
        "id": 83,
        "description": "A group of boys trespassed into a graveyard at night, dug up a grave, and stole jewellery from the corpse.",
        "offense_category": "trespass on burial place and theft",
        "expected_bns_sections": ["301", "303", "329"],
        "offense_keywords": ["graveyard", "trespass", "grave robbery", "corpse", "burial place"],
        "key_issues": [
            "trespassing on burial place",
            "offering indignity to dead body",
            "theft from grave",
            "criminal trespass",
        ],
    },
    {
        "id": 84,
        "description": "A man disrupted a prayer meeting in a mosque by shouting slogans and throwing shoes inside.",
        "offense_category": "disturbing religious assembly",
        "expected_bns_sections": ["300", "298"],
        "offense_keywords": ["disturbing prayer", "mosque", "religious assembly", "slogans", "disruption"],
        "key_issues": [
            "disturbing religious assembly",
            "voluntary disturbance of worship",
            "insulting religion of a class",
        ],
    },
    {
        "id": 85,
        "description": "My neighbour entered my house without permission while I was away and rearranged furniture and left a threatening note.",
        "offense_category": "criminal trespass and intimidation",
        "expected_bns_sections": ["329", "332", "351"],
        "offense_keywords": ["trespass", "entering house", "threatening note", "without permission", "intimidation"],
        "key_issues": [
            "criminal trespass into dwelling",
            "entering to commit offence",
            "criminal intimidation",
        ],
    },
    {
        "id": 86,
        "description": "A drunk man created a ruckus at a railway station, used filthy language, and urinated on the platform in front of passengers.",
        "offense_category": "misconduct by drunken person",
        "expected_bns_sections": ["355", "270", "296"],
        "offense_keywords": ["drunken misconduct", "public nuisance", "obscene behaviour", "railway station"],
        "key_issues": [
            "misconduct in public by drunken person",
            "public nuisance",
            "obscene act in public place",
        ],
    },
    {
        "id": 87,
        "description": "During a quarrel over water, my neighbour intentionally insulted me in front of the entire colony trying to provoke me to fight.",
        "offense_category": "intentional insult to provoke breach of peace",
        "expected_bns_sections": ["352"],
        "offense_keywords": ["insult", "provocation", "breach of peace", "quarrel", "public humiliation"],
        "key_issues": [
            "intentional insult with intent to provoke",
            "breach of public peace",
            "provoking violence",
        ],
    },
    # ── Cases 88-93: Forgery / Counterfeiting ───────────────────────────
    {
        "id": 88,
        "description": "Police found a printing press in my area that was producing fake two-thousand rupee notes.",
        "offense_category": "counterfeiting currency",
        "expected_bns_sections": ["178", "181"],
        "offense_keywords": ["counterfeiting", "fake currency", "printing press", "rupee notes", "forgery"],
        "key_issues": [
            "counterfeiting currency notes",
            "making instruments for counterfeiting",
            "possession of counterfeiting material",
        ],
    },
    {
        "id": 89,
        "description": "A person paid me with fake five-hundred rupee notes for goods I sold; I realized later when the bank rejected them.",
        "offense_category": "using counterfeit currency",
        "expected_bns_sections": ["179", "180"],
        "offense_keywords": ["counterfeit notes", "fake currency", "bank rejection", "using as genuine"],
        "key_issues": [
            "using counterfeit currency as genuine",
            "possession of counterfeit notes",
            "knowingly passing fake notes",
        ],
    },
    {
        "id": 90,
        "description": "A man forged a court order and used it to claim ownership of my ancestral property at the registrar's office.",
        "offense_category": "forgery of court record",
        "expected_bns_sections": ["336", "337", "340"],
        "offense_keywords": ["forgery", "court order", "property", "fake document", "registrar"],
        "key_issues": [
            "forgery of record of court",
            "using forged document as genuine",
            "attempt to dispossess rightful owner",
        ],
    },
    {
        "id": 91,
        "description": "Someone created a fake will in my deceased father's name to claim his property, forging his signature and a witness's signature.",
        "offense_category": "forgery of will",
        "expected_bns_sections": ["336", "338", "335"],
        "offense_keywords": ["forged will", "fake signature", "property dispute", "inheritance", "forgery"],
        "key_issues": [
            "forgery of will",
            "forging signature of deceased",
            "fraudulent claim to property",
            "making false document",
        ],
    },
    {
        "id": 92,
        "description": "A shopkeeper in our area has been using fake stamp papers for executing property agreements.",
        "offense_category": "counterfeiting government stamps",
        "expected_bns_sections": ["178", "179"],
        "offense_keywords": ["fake stamps", "counterfeit", "stamp paper", "government stamp", "forgery"],
        "key_issues": [
            "counterfeiting government stamps",
            "using counterfeit stamps as genuine",
            "executing agreements on fake stamp paper",
        ],
    },
    {
        "id": 93,
        "description": "An employee of a firm altered financial records in the company's accounting software to hide his embezzlement.",
        "offense_category": "falsification of accounts",
        "expected_bns_sections": ["344", "314"],
        "offense_keywords": ["falsification", "accounts", "embezzlement", "tampering", "records"],
        "key_issues": [
            "falsification of books of account",
            "dishonest alteration of records",
            "concealing misappropriation",
        ],
    },
    # ── Cases 94-100: Mixed / Complex Multi-section Cases ───────────────
    {
        "id": 94,
        "description": "A drug dealer was caught selling narcotic substances near a school and was also found with a licensed firearm which he used to threaten buyers who owed him money.",
        "offense_category": "drug offences with extortion",
        "expected_bns_sections": ["308", "351", "270"],
        "offense_keywords": ["drugs", "narcotics", "school", "firearm", "extortion", "threatening"],
        "key_issues": [
            "selling narcotics near educational institution",
            "possession and use of firearm for intimidation",
            "extortion from buyers",
            "public nuisance",
        ],
    },
    {
        "id": 95,
        "description": "An organized gang has been operating a fake call center, impersonating tax officials, and extorting money from people threatening them with arrest.",
        "offense_category": "organised crime / cheating / extortion",
        "expected_bns_sections": ["111", "319", "308", "318"],
        "offense_keywords": ["organised crime", "fake call center", "impersonation", "extortion", "tax fraud"],
        "key_issues": [
            "organised criminal activity",
            "cheating by personation",
            "extortion by threat of arrest",
            "large-scale fraud",
        ],
    },
    {
        "id": 96,
        "description": "During communal riots, a mob set fire to several houses and a member of the mob raped a woman whose family was fleeing.",
        "offense_category": "rioting, arson, and rape",
        "expected_bns_sections": ["191", "326", "63", "65"],
        "offense_keywords": ["communal riot", "arson", "rape", "mob violence", "fire"],
        "key_issues": [
            "rioting with deadly weapons",
            "mischief by fire",
            "rape during communal violence",
            "aggravated sexual assault",
        ],
    },
    {
        "id": 97,
        "description": "A known terrorist group planted a bomb in a market killing five people and injuring dozens.",
        "offense_category": "terrorist act",
        "expected_bns_sections": ["113", "101", "103"],
        "offense_keywords": ["terrorism", "bomb blast", "explosion", "killing", "market"],
        "key_issues": [
            "terrorist act causing death",
            "use of explosive substance",
            "mass casualties",
            "intent to strike terror",
        ],
    },
    {
        "id": 98,
        "description": "A doctor at a government hospital demanded Rs 50,000 from a poor patient's family to perform an emergency surgery and refused to treat without payment.",
        "offense_category": "non-treatment of victim and extortion",
        "expected_bns_sections": ["200", "308"],
        "offense_keywords": ["non-treatment", "doctor", "extortion", "hospital", "emergency"],
        "key_issues": [
            "refusing treatment of victim",
            "public servant demanding illegal gratification",
            "putting person in fear to extract money",
        ],
    },
    {
        "id": 99,
        "description": "A woman mixed poison into her husband's food intending to kill him but he survived after being rushed to hospital; she was also found to have taken a large life insurance policy on him a week before.",
        "offense_category": "attempt to murder and poisoning",
        "expected_bns_sections": ["109", "123", "61"],
        "offense_keywords": ["attempt to murder", "poisoning", "life insurance", "wife", "conspiracy"],
        "key_issues": [
            "attempt to commit murder",
            "administering poison with intent to commit offence",
            "criminal conspiracy",
            "premeditation evidenced by insurance",
        ],
    },
    {
        "id": 100,
        "description": "A group of men forcibly entered a Dalit family's home, beat them severely for drawing water from the village well, destroyed their household items, and hurled casteist slurs at them in front of the village.",
        "offense_category": "caste violence / rioting / mischief / hurt",
        "expected_bns_sections": ["189", "191", "117", "324", "196"],
        "offense_keywords": ["caste violence", "Dalit", "rioting", "assault", "mischief", "discrimination"],
        "key_issues": [
            "unlawful assembly and rioting",
            "voluntarily causing grievous hurt",
            "mischief and destruction of property",
            "promoting enmity on grounds of caste",
            "discrimination against scheduled caste",
        ],
    },
]
